// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project Market
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faMarketAsset from '@/i18n/market-asset/fa.json';
import enMarketAsset from '@/i18n/market-asset/en.json';
import faMarketAssetType from '@/i18n/market-asset-type/fa.json';
import enMarketAssetType from '@/i18n/market-asset-type/en.json';
import faMarketSector from '@/i18n/market-sector/fa.json';
import enMarketSector from '@/i18n/market-sector/en.json';
import faMarketType from '@/i18n/market-type/fa.json';
import enMarketType from '@/i18n/market-type/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'market-asset': faMarketAsset,
  'market-asset-type': faMarketAssetType,
  'market-sector': faMarketSector,
  'market-type': faMarketType,
  },
  en: {
  'market-asset': enMarketAsset,
  'market-asset-type': enMarketAssetType,
  'market-sector': enMarketSector,
  'market-type': enMarketType,
  },
} as const;
